services:
  fuzzbin:
    # https://github.com/asotbz/Fuzzbin
    image: ghcr.io/asotbz/fuzzbin:0.4.1
    security_opt:
      - no-new-privileges=true
    container_name: fuzzbin
    restart: unless-stopped
    labels:
      stack-back.volumes: true
      stack-back.volumes.include: "fuzzbin_config"

      # logs collection
      logging: promtail
      logging_jobname: containerlogs
      stackname: xfer

    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: 1
        tag: "{{.Name}}"
    volumes:
      - fuzzbin_config:/config
      - /var/media/music_videos:/music_videos
    network_mode: service:gluetun
    
volumes:
  fuzzbin_config:
